### ISSUE TITLE
[FIX] Home View 네비게이션바로 변환

### ISSUE THREAD

**Issue by Betmoong** [umc-bonheur/bonheur-ios#10]
## 💡 Issue

HomeView의 아래 빨간색 네모 상자 부분을 네비게이션 바로 수정

## 📝  todo

- [x] 빨간색 네모 상자 부분을 네비게이션 바로 수정
- [x] 네비게이션바 크기가 기본 네비게이션바보다 크므로 커스텀 네비게이션바 사용
- [x] 캘린더 버튼을 누르면 네비게이션 형식으로 캘린더뷰로 넘어가기

## 📸 Screenshot

<img width="250" alt="image" src="https://user-images.githubusercontent.com/100567791/212121719-f3ac93d5-0c65-4929-8e72-5633037b8a58.png">

**Comment by Betmoong** [comment]
https://stackoverflow.com/questions/66235384/xcode-12-change-the-size-of-the-navigation-bar-self-navigationcontroller

iOS 11 이후 애플에서 네비게이션바의 높이 조절을 막았다고 합니다.
따라서, 커스텀 네비게이션바 구현 필요.

**Comment by Betmoong** [comment]
Home View 네비게이션바로 변환 작업 취소(1.13일 회의)
