### ISSUE TITLE
[FEAT] 행복 기록 작성 View 구현

### ISSUE THREAD

**Issue by leeeeeyeon** [umc-bonheur/bonheur-ios#15]
## 💡 Issue

행복 기록 작성 View 구현

## 📝  todo
- [x] 전체적인 UI Component 배치
- [ ] 해시태그 Half Modal View
- [ ] 카메라&갤러리에 접근하여 사진 선택하기
- [x] 선택된 사진 확인하는 View
- [x] 텍스트 작성 View

## 📸 Screenshot

|처음 들어갔을 때|내용 입력 후|
|:---:|:---:|
|<img width="250" src="https://user-images.githubusercontent.com/65899774/212450231-ba3d2e28-d51a-4a01-ad01-74da5e2cf904.png">|<img width="250" src="https://user-images.githubusercontent.com/65899774/212450256-758fde52-269b-4461-bc14-c510f600e4d8.png">|<img width="250" src="https://user-images.githubusercontent.com/65899774/212450256-758fde52-269b-4461-bc14-c510f600e4d8.png">|

|해시태그 선택|사진 선택|
|:---:|:---:|
|<img width="250" src="https://user-images.githubusercontent.com/65899774/212450242-c4147609-29ff-445f-85d0-d63183eb3f94.png">|<img width="250" src="https://user-images.githubusercontent.com/65899774/212450339-efb5df11-062d-4e79-950b-819abcc42396.png">|
