### ISSUE TITLE
[FEAT] HomeView 구현(2)

### ISSUE THREAD

**Issue by SohyeonKim-dev** [umc-bonheur/bonheur-ios#16]
## 💡 Issue
- TabBar Custom 구현하기
- HomeView 및 CollectionView Cell 수정
- 코드 리뷰 수정사항 반영하기 (폰트 변경, 더보기 기능 구현)
- SceneDelegate UserDefaults 구현

## 📝  todo
- [ ] TabBar Custom
- [ ] CollectionView Cell 더보기 구현
- [x] Font 코드 수정
- [x] SceneDelegate UserDefaults 구현
- [x] Default 홈화면 구현하기

## 📸 Screenshot
![홈화면 6](https://user-images.githubusercontent.com/82718756/212459684-1625c8cf-d463-47ec-8376-2e138a34b4fd.svg)
![홈화면 4](https://user-images.githubusercontent.com/82718756/212459685-af05a6e9-b057-463d-9bcc-cecb5a54c4ae.svg)
