### ISSUE TITLE
[FEAT] Home View 구현 

### ISSUE THREAD

**Issue by SohyeonKim-dev** [umc-bonheur/bonheur-ios#2]
## 💡 Issue
- main view 구현

## 📝  todo
- [x] 전반적인 UI Component 구현
- [x] collectionView 구현
- [x] cell / stackView 구현
- [ ] tab bar custom / half-modal view 조사하기 

## 📸 Screenshot
![홈화면 6](https://user-images.githubusercontent.com/82718756/211519298-c9a18d21-b9de-466f-9db1-a4a43a5387ec.png)
