### ISSUE TITLE
[FEAT] Half-modal View 구현하기

### ISSUE THREAD

**Issue by SohyeonKim-dev** [umc-bonheur/bonheur-ios#20]
## 💡 Issue
- Half-modal View 구현
- 최근 사용 StackView 구현 고민하기
- 기록 화면에서의 재사용성 고려하기
- UI Divider extension 추가하기 (선 UI)

## 📝  todo
- [x] Half-modal 구현
- [ ] StackView 구현
- [x]  UI Divider extension 추가
- [ ] 태그의 터치 기능 (X) 구현

## 📸 Screenshot
![Halfmodal](https://user-images.githubusercontent.com/82718756/214032310-6e6ec1ca-abee-4721-b011-89c7db5fce70.svg)
