### ISSUE TITLE
[FEAT] 설정 View 구현

### ISSUE THREAD

**Issue by vvtkfkddl11** [umc-bonheur/bonheur-ios#21]
## 💡 Issue
설정 View 구현

## 📝  todo
- [x] 설정 화면 UI 구현
- [ ] 회원탈퇴 Alert UI 구현
- [x] 푸쉬 알림 화면 UI 구현
- [x] 개발자 소개 UI 구현

## 📸 Screenshot
![마이페이지 - 설정 (2)](https://user-images.githubusercontent.com/77392642/214779759-ca2aad16-bde7-4906-8584-a9443c47ef4f.png)
