### ISSUE TITLE
[FEAT] CalendarView 구현(3)

### ISSUE THREAD

**Issue by Betmoong** [umc-bonheur/bonheur-ios#32]
## 💡 Issue

- 오늘 날짜를 선택했을 경우 날짜의 text color가 검정으로 변하는 문제 수정하기
- todayButton 클릭 시 오늘 날짜의 text color가 검정으로 변하는 문제 수정하기
- week 모드에서 이전, 다음 버튼을 눌렀을 때 월 단위로 바뀌는 문제 수정하기
- 선택한 날짜 text를 Bold 체로 변경하기
## 📝  todo

- [x] 오늘 날짜를 선택했을 경우 오늘 날짜의 text color가 검정으로 변하는 문제 수정
- [x] todayButton 클릭 시 오늘 날짜의 text color가 검정으로 변하는 문제 수정
- [x] week 모드에서 이전, 다음 버튼을 눌렀을 때 월 단위로 바뀌는 문제 수정(주 단위로 바뀌도록 수정)
- [x] 선택한 날짜 text를 Bold체로 변경
## 📸 Screenshot

|행복 기록 추가|week 버튼 월 단위 문제|
|:---:|:---:|
|<img width="250" src="https://user-images.githubusercontent.com/100567791/215804072-92da2f70-7989-491e-abd3-50acd2215a01.png">|<img width="250" src="https://user-images.githubusercontent.com/100567791/215808866-0ed2a9c7-a71b-477d-a642-75d1ba24c85a.gif">|
