### ISSUE TITLE
[FEAT] 마이페이지 통계 API 연동 및 UI 다듬기

### ISSUE THREAD

**Issue by vvtkfkddl11** [umc-bonheur/bonheur-ios#47]
## 💡 Issue
마이페이지 통계 API 연동

## 📝  todo
- [ ] 활동 종합 조회 API 연동
- [ ] 활동 월별 조회 API 연동
- [ ] 활동 요일별 조회 API 연동
- [ ] 활동 시간별 조회 API 연동
- [ ] 활동 태그별 조회 API 연동
